"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables once
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-6drttg+21y9atlm@@!5%6aqs9&t8&zglt#i-jjz^f3ah#0ftua",
)



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")
# Application definition
# 1. Allow the domain to serve the app
ALLOWED_HOSTS = [
    'whatsapp-1-vectra-app.xqqhik.easypanel.host', 
    'localhost', 
    '127.0.0.1',
]

# 2. Trust the origin for CSRF (This is the critical part for your error)
CSRF_TRUSTED_ORIGINS = [
    'https://whatsapp-1-vectra-app.xqqhik.easypanel.host'
]

# 3. Ensure cookies work over HTTPS (Since Easypanel uses SSL)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for allauth
    # Third-party apps
    "rest_framework",  # Django REST Framework
    "drf_spectacular",  # API Documentation
    "corsheaders",  # CORS Headers
    "idempotency_key",  # Idempotency
    "phonenumber_field",
    "django_htmx",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # Local apps
    "hr",
    "employees",
    "analytics",
    "ats",
    "leave",
    "notifications",
    "onboarding",
    "org",
    "payroll",
    "rbac",
    "talent",
    "workflow",
    "users",
    "attendance",
    "discipline",
    "development",
    "engagement",
    "benefits",
    "performance",
    "core",
    
     "crispy_forms",
    "crispy_bootstrap5", 
    'tinymce',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # ✅ CORS Middleware (Must be before CommonMiddleware)
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "users.middleware.ThreadLocalMiddleware",  # Capture context for logging
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.tenant_branding",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"

# Database
# Database
# DATABASE_URL = os.environ.get("DATABASE_URL")

# if DATABASE_URL:
#     DATABASES = {
#         "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600),
#     }
# else:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "db.sqlite3",
#         }
#     }
    
# DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "db.sqlite3",
#         }
#     }


# settings.py
# settings.py

# 1. Try to get the URL from environment
env_db_url = os.getenv("DATABASE_URL1")

if env_db_url:
    DATABASES = {
        'default': dj_database_url.config(default=env_db_url, conn_max_age=600)
    }
else:
    # 2. Hardcoded Fallback (Your Postgres Server)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'whatsapp-1',
            'USER': 'postgres',
            'PASSWORD': '851fa108b40cc528ea77',
            'HOST': '147.182.194.8',
            'PORT': '5431',
        }
    }

# 3. Add this temporary debug line to your terminal
print(f"--- DEBUG: Using Database Engine: {DATABASES['default'].get('ENGINE')} on {DATABASES['default'].get('HOST')} ---")
# Password validation
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]  # If you have a global static folder

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
#  Authentication & Allauth
# ==============================================================================
SITE_ID = 1
AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email", "password1"]  # Simplified
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ADAPTER = "users.adapter.MySocialAccountAdapter"
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"

LOGIN_URL = "users:login"
LOGOUT_REDIRECT_URL = "users:login"
LOGIN_REDIRECT_URL = "users:home"

# ==============================================================================
#  API & REST Framework
# ==============================================================================
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}


SPECTACULAR_SETTINGS = {
    "TITLE": "HRIS API",
    "DESCRIPTION": "Combined API schema for HRIS modules (Org, Employees, Attendance, Development, Discipline, Engagement, Benefits, ATS, etc.)",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# ==============================================================================
#  CORS
# ==============================================================================
CORS_ALLOW_ALL_ORIGINS = True  # Setup for development; restrict in production
CORS_ALLOW_CREDENTIALS = True

# ==============================================================================
#  Logging
# ==============================================================================
LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)

APP_NAMES = [
    "hr",
    "employees",
    "analytics",
    "ats",
    "leave",
    "notifications",
    "onboarding",
    "org",
    "payroll",
    "rbac",
    "talent",
    "workflow",
    "users",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "context_filter": {
            "()": "users.logging_filters.ContextFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} | {levelname} | [{app_name}] | {tenant} | {user} | {message}",
            "style": "{",
        },
        "server": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["context_filter"],
        },
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "debug.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["context_filter"],
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "error.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "filters": ["context_filter"],
        },
        "server_console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "server",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_error"],
            "level": "INFO",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "": {
            "handlers": ["console", "file_debug", "file_error"],
            "level": "DEBUG",
        },
    },
}


# ==============================================================================
#  Email & Third Party Services
# ==============================================================================
SITE_URL = "http://localhost:8000"
SITE_DOMAIN = "https://dignityconcept.tech"


# Email configuration for Dignity Concept Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # ✅ This is essential
EMAIL_PORT = 587

EMAIL_USE_TLS = True # ✅ use STARTTLS 
EMAIL_USE_SSL = False

EMAIL_HOST_USER = "upwardwave.dignity@gmail.com"
EMAIL_HOST_PASSWORD = "obwrxlfyamlclvdx"
DEFAULT_FROM_EMAIL = 'Dignity Concept <upwardwave.dignity@gmail.com>'


# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "mail.dignityconcept.tech"
# EMAIL_PORT = 465
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
# EMAIL_HOST_USER = "solutions@dignityconcept.tech"
# EMAIL_HOST_PASSWORD = "d~Gg@KKEUm-_QVw~"
# DEFAULT_FROM_EMAIL = "Dignity Concept <solutions@dignityconcept.tech>"

STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")

PAYPAL_BASE_URL = "https://api.sandbox.paypal.com"
PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"




# Celery Configuration


# CELERY_RESULT_BACKEND = 'redis://:@Ajibandele1604%@192.168.77.145:6379/0' 
CELERY_BROKER_URL = 'redis://:@Ajibandele1604%@192.168.106.145:6379/0' 
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'   #cusotmize
CELERY_RESULT_EXTENDED = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'



CELERY_BEAT_SCHEDULE = {
    'nag-managers-every-hour': {
        'task': 'workflow.tasks.send_workflow_nag_emails',
        'schedule': 3600.0, # Every hour (in seconds)
    },
    'escalate-workflows-every-midnight': {
        'task': 'workflow.tasks.run_workflow_escalations',
        'schedule': 86400.0, # Every 24 hours
    },
    'check-crm-stagnation-daily': {
        'task': 'workflow.tasks.check_crm_stale_opportunities',
        'schedule': 86400.0, # Daily
    },
    'check-procurement-deadlines-every-4-hours': {
        'task': 'workflow.tasks.check_procurement_deadlines',
        'schedule': 14400.0, # Every 4 hours
    },
}



LINKEDIN_CLIENT_ID="86t0k0xq9pd4gq"
LINKEDIN_ACCESS_TOKEN=os.getenv("LINKEDIN_ACCESS_TOKEN", "AQWleb3YKKGZbbAUrfm0YPbjczTf211Brbwm85jAZ5e9gG0AT2D_6gYm2qAVnDWkFbDs2u0VAbYWnkJpm8GOVY72BkPisAk1oZP7idHau31l5SnCuazfCSEO-TAH-lmlRx-EwfmPj8yS_VvY2goDRK-TVFrM0qbfqU5DSJuYAj_rrU0UGb7sV-SmItjA7SjbNgKsFKjYd6xtGrRc9I43NGB88hc2gqOlTDU74Al8KYbXkZG0ufOuZCrIRWCmtsvgQuMwX4Wjc3mR-ZquGoqVJbjpICLeUNIYRc-nwL8oU3elZqePlaPR7y0zd_cJJijN60htT_v15fGdAIfekF2jQl46IGD0OQ")
LINKEDIN_CLIENT_SECRET=os.getenv("LINKEDIN_CLIENT_SECRET", "WPL_AP1.TXdsMlyfVAcROvfL.BINVNg==") 
LINKEDIN_REDIRECT_URI="http://127.0.0.1:8000/linkedin/callback/"


TINYMCE_DEFAULT_CONFIG = {
    'height': 560,
    # 'width': 600,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen insertdatetime nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists charmap print hr
            anchor pagebreak advlist autolink lists link image charmap print preview anchor spellchecker
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            link image media | codesample
            ''',
    # 'toolbar2': '''
    #         undo redo | cut copy paste | styleselect | searchreplace | 
    #         visualblocks visualchars | code | insertdatetime nonbreaking |
    #         charmap hr pagebreak | save
    #         ''',

         "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",

    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    'branding': False, 
    'promotion': False,
    # "language": "es_ES",
}